---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


electricShine has a function `buildPackage()` which wraps all of the other functions and provides an easy-api for generating simple apps. 

Take for example:
```{r eval = FALSE}

electricShine::buildPackage(
  appName = "My_App",
  semanticVersion = "1.0.0",
  installTo = tempdir(),
  MRANdate = as.character(Sys.Date() - 3),
  functionName = "run_app",
  githubRepo = "chasemc/demoApp",
  localPath  = NULL,
  only64 = TRUE
)
```

Walking through this line-by-line:

- `electricShine::buildPackage()`
  - This is the main API for electricShine, which calls all of the funtions necessary to create an Electron app from a shiny app.
 
- `appName = "My_App",`
  - This is the name that will be displayed on the top of the chromium window of the Electron app, as well as part of the name of the installation file. This is what end-users would say is the name of your app. 

- `semanticVersion = "1.0.0",`
  - String with the app version #. For info on semantic versioning see: https://semver.org/
  
- `installTo = tempdir(),`
  - Directory where the Electron app will be built. Best if it's on the same drive as R that's calling electtric Shine.
  
- `MRANdate = as.character(Sys.Date() - 3),`
  - Date in the format YYYY-MM-DD. R, and all R packages for the Electron app will be downloaded from MRAN, with the given snapshot date. The version of R being used to run electricShine must match the version of R available as the main release on this date.
  
- `functionName = "run_app",`
  - A string specifying the name of the function that starts your shiny app.
  - In this case  "run_app" https://github.com/chasemc/demoApp/blob/master/R/run_app.R
  - See https://github.com/ThinkR-open/golem for info on how to setup this kind of function and shiny app.
  
- `githubRepo = "chasemc/demoApp",`
  - You have the option of choosing a public GitHub repo (PR for supporting private repos welcome) as where the shiny app is installed from.
  - Here we are taking a shiny app, written as an R package and located at https://github.com/chasemc/demoApp  

- `localPath  = NULL,`
  - Alternatively you can specify a local path as the location of the shiny app that you want to use. 

Only one of `githubRepo` or `localPath`should have a specified value, the other should be unassigned, or assigned NULL.
  
- `only64 = TRUE  `
  - If `TRUE`, the R installation will be trimmed to remove 32-bit dlls. If FALSE, then 32 and 64 bit R will be packaged with the app. 
  
  
  

Here we are taking a shiny app, written as an R package and located at `github.com/chasemc/demoApp`.

